### ISSUE TITLE
error when uploading JustEnoughScalaForSpark.snb

### ISSUE THREAD

**Issue by leoSeattle** [deanwampler/JustEnoughScalaForSpark#4] opened 2017-04-19 06:08 UTC
The message is:

The error was: SyntaxError: JSON.parse: unexpected character at line 7 column 1 of the JSON data

**Comment by leoSeattle** [comment] 2017-04-19 06:39
Here is error in terminal:

[INFO] View notebook 'JustEnoughScalaForSpark.snb', presentation: 'None'
[INFO] getNotebook at path JustEnoughScalaForSpark.snb
[INFO] Loading notebook at path JustEnoughScalaForSpark.snb
[ERROR] Error accessing notebook [JustEnoughScalaForSpark]
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.StringReader@3d9c358b; line: 7, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1419)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:437)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1462)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:683)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3105)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3024)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1652)
	at play.api.libs.json.JacksonJson$.parseJsValue(JsValue.scala:485)
	at play.api.libs.json.Json$.parse(Json.scala:19)
	at notebook.NBSerializer$.read(NBSerializer.scala:253)
	at notebook.server.NotebookManager.load(NotebookManager.scala:141)
	at notebook.server.NotebookManager.getNotebook(NotebookManager.scala:90)
	at controllers.Application$.getNotebook(Application.scala:646)
	at controllers.Application$$anonfun$contents$1.apply(Application.scala:323)
	at controllers.Application$$anonfun$contents$1.apply(Application.scala:290)
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:433)
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:432)
	at play.api.mvc.Action$.invokeBlock(Action.scala:556)
	at play.api.mvc.Action$.invokeBlock(Action.scala:555)
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:518)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128)
	at scala.Option.map(Option.scala:146)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121)
	at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:705)
	at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:705)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by deanwampler** [comment] 2017-04-20 12:31
I can't reproduce it. Can you confirm that you are using the latest version on the master branch? That's what I just tried. 

Is it possible that the `.snb` file was  modified accidentally? If it seems fine, attach the whole thing to a reply and I'll look at. Also, tell me what version of Spark Notebook you are running and your operating system. Thanks.

**Comment by deanwampler** [comment] 2018-07-02 12:11
Closing this, as I switched the project to Jupyter and changed the way you run it so that it's no longer necessary to upload the notebook to the environment.

**Closed by deanwampler** 2018-07-02 12:11 UTC
